# Generated by Django 4.0.5 on 2022-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uniqueID', models.UUIDField(primary_key=True, serialize=False)),
                ('img', models.TextField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
