# Generated by Django 4.0.5 on 2022-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.TextField(default='', max_length=255),
        ),
    ]
